config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "news#index"
  resources :users
  resources :news
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :user
    has_one_attached :thumbnail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :news, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    @news.user_id = current_user.id
    @news.save
    redirect_to news_path(@news)
  end


  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    @news.update(news_params)
    redirect_to news_path(@news)
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to user_path(news.user), notice: "記事を削除しました。"
  end

  private
  def news_params
  params.require(:news).permit(:title, :body, :thumbnail)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    redirect_to news_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :address, :profile, :avatar, :news)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newses_helper.rb
module NewsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/show.html.erb
<p>
Welcome to Show Page
</p>

<p>
<%= image_tag 'no-image.png', :alt => '登録ボタン' %>
</p>

<p>
<%= image_tag 'app/assets/images/no-image.png' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Localsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/d76866717a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title" style="font-family: normal;">Local Infomation</h1>
    <% end %>
    
    
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="field is-grouped">
          <p class="control">
            <%= link_to "ショップ一覧", users_path, class:  "button is-warning is-light" %>
            <%= link_to "記事一覧", news_index_path, class: "button is-warning is-light" %>
            <%= link_to "新規投稿", new_news_path, class: "button is-warning is-light" %>
          </p>
          <p class="control">
            <% if user_signed_in? %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"button is-warning is-light" %>
              <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
            <% else %>
              <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
              <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
              
            <% end %>
          </p>
        </div>
      </div>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/news/edit.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿編集
      </h1>
    </div>
  </div>
</section>

<% if @news.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@news.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @news.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @news do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "内容", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "写真", class: "label" %>
            <%= f.file_field :thumbnail %>
          </div>

          <%= f.submit '投稿', class: "button is-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/news/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        記事一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @news.each do |news| %>
        <div class="column is-8">
          <div class="card">
            <div class="card-image">
              <figure class="image is-3by6">
                <%= link_to news_path(news) do %>
                  <% if news.thumbnail.attached? %>
                    <%= image_tag news.thumbnail %>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    
                  </figure>
                </div>
                <div class="media-content">
                  <b><%=link_to news.user.username, user_path(news.user) %></b>
                  <div class="title"><%=link_to news.title, news_path(news) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= news.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/news/new.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿　作成
      </h1>
    </div>
  </div>
</section>


<% if @news.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@news.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @news.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @news do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "コンテンツ", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.file_field :thumbnail %>
          </div>

          <%= f.submit '投稿', class: "button is-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/news/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        コンテンツ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
         <% if @news.thumbnail.attachment.present? %>
          <div class="card-image">
            <figure class="image is-4by3">
              <%= image_tag @news.thumbnail %>
            </figure>
          </div>
         <% end %>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @news.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>ニュース</th>
                </tr>
                <tr>
                  <td><%= simple_format @news.body %></td>
                </tr>
              </table>
             
                
              
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-warning">
          <p class="panel-heading">
            By <%= @news.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @news.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@news.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @news.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
  
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :address, "所在地", class: "label" %>
            <%= f.text_field :address, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.file_field :avatar %>
          </div>

          <%= f.submit "更新", class: "button is-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</section>
</html>

app/views/users/index.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        登録ショップ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline ">
      <% @users.each do |user| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= link_to user_path(user) do %>
                      <% if user.avatar.attached? %>
                        <%= image_tag user.avatar %>
                      <% end %>
                    <% end %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数を表示したい
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
            　<% if @user.avatar.attached? %>
            　　<%= image_tag @user.avatar %>
          　　<% end %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-warning" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user&.profile %>
                  <iframe src="https://www.google.com/maps/embed/v1/place?q=<%= @user.address %>&key=AIzaSyDf1XUycvPXTkcXIKMnroQgSRaSX7x4S1U"></iframe>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.news.each do |news| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <% if news.thumbnail.attached? %>
                  <%= image_tag news.thumbnail %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <strong><%= news.title %></strong>
                  <%= link_to news_path(news), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_news_path(news), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to news_path(news), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= news.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>